name: Random Dependent Jobs Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 Step
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Job 2 Step
        run: echo "This is Job 2, depending on Job 1"

  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
      - name: Job 3 Step
        run: echo "This is Job 3, depending on Job 2"

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - name: Job 4 Step
        run: echo "This is Job 4, depending on Job 2 and Job 3"

  job5:
    runs-on: ubuntu-latest
    needs: [job4]
    steps:
      - name: Job 5 Step
        run: echo "This is Job 5, depending on Job 4"

  job6:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
      - name: Job 6 Step
        run: echo "This is Job 6, depending on Job 3"

  job7:
    runs-on: ubuntu-latest
    needs: [job5, job6]
    steps:
      - name: Job 7 Step
        run: echo "This is Job 7, depending on Job 5 and Job 6"

  job8:
    runs-on: ubuntu-latest
    needs: [job6]
    steps:
      - name: Job 8 Step
        run: echo "This is Job 8, depending on Job 6"

  job9:
    runs-on: ubuntu-latest
    needs: [job7, job8]
    steps:
      - name: Job 9 Step
        run: echo "This is Job 9, depending on Job 7 and Job 8"

  job10:
    runs-on: ubuntu-latest
    needs: [job9]
    steps:
      - name: Job 10 Step
        run: echo "This is Job 10, depending on Job 9"
