name: Secrets

on:
  push:
    branches:
      - main

jobs:
  make-api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Using API key from env: $API_KEY"
