name: Workflow commands

on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        id: my_group
        run: |
          echo "::group: My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
          
      - name: "step 1"
        id: step1
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV

      - name: "Print MY_VAL"
        id: print_val
        run: |
          echo "MY_VAL is: $MY_VAL"
